### ISSUE TITLE
Disponibilizar um endpoint para buscar as informações de congregação

### ISSUE THREAD

**Issue by eduardodallmann** [eduardodallmann/jw#5]
endpoint congregacao?congregacaoId=42342342

validações: apenas usuário com permissão de visualização ou edição de informacoesCongregacao pode acessar

Retornar um json com os dados:
id
nome
numero
reuniaoFinalSemanaDia
reuniaoFinalSemanaHorario
reuniaoMeioSemanaDia
reuniaoMeioSemanaHorario
zoomId
zoomSenha
zoomLink
enderecoSalao
circuito
nomeSC

**Comment by Rodrigusto** [comment]
fechei sem querer :(
